// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTk4_48Sod-PLhBWo64-oNPPyTM1_JaxY',
    appId: '1:517981565770:web:e8b8985e83499bce55c7b3',
    messagingSenderId: '517981565770',
    projectId: 'skyballoon-ab8e5',
    authDomain: 'skyballoon-ab8e5.firebaseapp.com',
    databaseURL: 'https://skyballoon-ab8e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skyballoon-ab8e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF3DlvG5aGExd1hcgxIm8Ptoltr_zIMvw',
    appId: '1:517981565770:android:9173dcdef3971de555c7b3',
    messagingSenderId: '517981565770',
    projectId: 'skyballoon-ab8e5',
    databaseURL: 'https://skyballoon-ab8e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skyballoon-ab8e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY-nP3plslmwpTH3UGx_i5-Tvh7uWFPMs',
    appId: '1:517981565770:ios:832e6120cf76e2c955c7b3',
    messagingSenderId: '517981565770',
    projectId: 'skyballoon-ab8e5',
    databaseURL: 'https://skyballoon-ab8e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skyballoon-ab8e5.firebasestorage.app',
    iosBundleId: 'com.example.skyVisionControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY-nP3plslmwpTH3UGx_i5-Tvh7uWFPMs',
    appId: '1:517981565770:ios:832e6120cf76e2c955c7b3',
    messagingSenderId: '517981565770',
    projectId: 'skyballoon-ab8e5',
    databaseURL: 'https://skyballoon-ab8e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skyballoon-ab8e5.firebasestorage.app',
    iosBundleId: 'com.example.skyVisionControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTk4_48Sod-PLhBWo64-oNPPyTM1_JaxY',
    appId: '1:517981565770:web:88402d07ce866d6e55c7b3',
    messagingSenderId: '517981565770',
    projectId: 'skyballoon-ab8e5',
    authDomain: 'skyballoon-ab8e5.firebaseapp.com',
    databaseURL: 'https://skyballoon-ab8e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skyballoon-ab8e5.firebasestorage.app',
  );

}